version = "1.2.0"

[httpd]
bind = "0.0.0.0"
port = "8001"

[protocol.unifi]
[protocol.unifi.reflector]
bind = "0.0.0.0"
port = "8002"

[protocol.rtsp]
[protocol.rtsp.ffmpeg_server]
bind = "0.0.0.0"
port = "8003"


